ChipShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    ]

coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='Количество:', min_value=0)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

coupons/forms.py
from django import forms


class CouponApplyForm(forms.Form):
    code = forms.CharField()

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


def cart_add(request, product_id):
    """Adding product into cart."""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                update_quantity=cd['update'])
    else:
        cart.add(product=product,
                quantity= 1,
                update_quantity= False)
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    """Removing product from cart."""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    """Reflecting content of cart."""
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form':coupon_apply_form})

cart/templates/cart/detail.html
{% extends "initial_base.html" %}
{% load static %}

{% block title %}Корзина{% endblock %}

{% block block_cart %}
            {% if cart %}
                <h1 class="decor cart">Корзина</h1>
                <table width="680px" cellspacing="0" cellpadding="5">
                          <tr bgcolor="#ddd">
                                <th width="220" align="left">Изображение </th>
                                <th width="180" align="left">Наименование </th>
                                <th width="100" align="center">Количество </th>
                                <th width="60" align="right">Цена </th>
                                <th width="60" align="right">Сумма </th>
                                <th width="90"> </th>
                          </tr>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr>
                                        <td>
                                            <a href="{{ product.get_absolute_url }}">
                                                {% if product.image %}
                                                    <img src="{{ product.image.url }}" width="150 px" height ="120 px">
                                                {% else %}
                                                    <img src="{% static 'image/no_image.png' %}" width="150 px" height ="100 px">
                                                {% endif %}
                                            </a>
                                        </td>
                                        <td>{{ product.name }}</td>
                                        <td>
                                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.update }}
                                                <input type="submit" value="Добавить">
                                                {% csrf_token %}
                                            </form>
                                        </td>
                                        <td align="right">{{ item.price }}</td>
                                        <td align="right">{{ item.total_price }}</td>
                                        <td align="center"> <a href="{% url 'cart:cart_remove' product.id%}"><img src="{% static 'images/delete.png' %}" class="remove" alt="remove" /><br />Удалить</a> </td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                            {% if cart.coupon %}
                                <tr>
                                    <td colspan="3" align="right"  height="30px">Всего&nbsp;&nbsp;</td>
                                    <td align="right" style=" font-weight:bold">  </td>
                                    <td align="right" style=" font-weight:bold">{{ cart.get_total_price }} </td>
                                    <td style=" font-weight:bold"> </td>
                                </tr>
                                <tr>
                                    <td colspan="3" align="right"  height="30px">Купон "{{ cart.coupon.code }}"(- {{ cart.coupon.discount }}%)&nbsp;&nbsp;</td>
                                    <td align="right" style=" font-weight:bold">   </td>
                                    <td align="right" style=" font-weight:bold">- {{ cart.get_discount|floatformat:"2" }} </td>
                                    <td style=" font-weight:bold"> </td>
                                </tr>
                            {% endif %}
                            <tr class="total">
                                <td>Итог</td>
                                <td colspan="4" class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} BYN</td>
                                <td class="num">
                                </td>
                            </tr>
                        </table>
                        <div class="cleaner h20"></div>
                        <div class="coupons">
                            <form action="{% url 'coupons:apply' %}" method="post">
                                <label for="id_code" class="coupons_label">Использовать купон:</label>
                                {{ coupon_apply_form.code }}
                                <input type="submit" value="Применить" class="apply_coupon" >
                                {% csrf_token %}
                            </form>
                        </div>

                        <div style="float:right; width: 215px; ">
                            <p><a href="{% url 'orders:order_create' %}">К оформлению</a></p>
                            <p><a href="javascript:history.back()">Вернуться к покупкам</a></p>
                        </div>
            {% else %}
                <div class="empty_cart">
                    <h1 class="decor cart">Ваша корзина пуста.</h1>
                    <img src="{% static 'images/empty.png' %}" class="empty" alt="empty" width="150 px" height ="150 px">
                </div>
            {% endif %}
        <div class="cleaner"></div>
{% endblock %}